<?php
/**
 * Application constants.
 */

// Shopping DB statuses
define('SHOPPING_STATUSES', ['부재', '재통', '가망', '계약완료', '안함']);
define('SHOPPING_DEFAULT_STATUS', '안함');

// Place DB statuses
define('PLACE_STATUSES', ['부재', '재통', '가망', '거절', '계약완료']);
define('PLACE_DEFAULT_STATUS', '부재');

// User roles
define('ROLE_ADMIN', 'ADMIN');
define('ROLE_EMPLOYEE', 'EMPLOYEE');
define('ROLES', [ROLE_ADMIN, ROLE_EMPLOYEE]);

// Pagination options
define('PAGE_SIZES', [50, 100, 300, 500, 1000]);
define('DEFAULT_PAGE_SIZE', 50);

// Session
define('SESSION_LIFETIME', 28800); // 8 hours in seconds

// Activity log action types
define('ACTION_LOGIN', 'LOGIN');
define('ACTION_LOGOUT', 'LOGOUT');
define('ACTION_USER_CREATE', 'USER_CREATE');
define('ACTION_USER_UPDATE', 'USER_UPDATE');
define('ACTION_USER_DELETE', 'USER_DELETE');
define('ACTION_COMPANY_CREATE', 'COMPANY_CREATE');
define('ACTION_COMPANY_UPDATE', 'COMPANY_UPDATE');
define('ACTION_COMPANY_CARRYOVER', 'COMPANY_CARRYOVER');
define('ACTION_SHOPPING_UPLOAD', 'SHOPPING_UPLOAD');
define('ACTION_SHOPPING_STATUS', 'SHOPPING_STATUS');
define('ACTION_SHOPPING_ASSIGN', 'SHOPPING_ASSIGN');
define('ACTION_SHOPPING_REVOKE', 'SHOPPING_REVOKE');
define('ACTION_PLACE_CREATE', 'PLACE_CREATE');
define('ACTION_PLACE_STATUS', 'PLACE_STATUS');
define('ACTION_PLACE_ASSIGN', 'PLACE_ASSIGN');
define('ACTION_PLACE_REVOKE', 'PLACE_REVOKE');
define('ACTION_MEMO_CREATE', 'MEMO_CREATE');
define('ACTION_EXCEL_DOWNLOAD', 'EXCEL_DOWNLOAD');

define('ACTIONS', [
    ACTION_LOGIN, ACTION_LOGOUT,
    ACTION_USER_CREATE, ACTION_USER_UPDATE, ACTION_USER_DELETE,
    ACTION_COMPANY_CREATE, ACTION_COMPANY_UPDATE, ACTION_COMPANY_CARRYOVER,
    ACTION_SHOPPING_UPLOAD, ACTION_SHOPPING_STATUS, ACTION_SHOPPING_ASSIGN, ACTION_SHOPPING_REVOKE,
    ACTION_PLACE_CREATE, ACTION_PLACE_STATUS, ACTION_PLACE_ASSIGN, ACTION_PLACE_REVOKE,
    ACTION_MEMO_CREATE, ACTION_EXCEL_DOWNLOAD,
]);

// Target types
define('TARGET_COMPANY', 'company');
define('TARGET_SHOPPING', 'shopping');
define('TARGET_PLACE', 'place');
define('TARGET_USER', 'user');
